disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Blog | Jundi Mubarok"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "/img/logo-header-putih.png"
  secondaryLogo = "/img/logo-header-hitam.png"
  description = "Ngobrol lewat tulisan ringan bersama Jundi Mubarok. Menghadirkan catatan harian, opini aplikasi, dan cerita perjalanan yang relatable untuk teman ngopi Kamu 😁"
  copyright = "Built with **Hugo** & [**Blowfish**](https://blowfish.page). Hosted on [**Netlify**](https://netlify.com)"

[params.author]
   name = "Jundi Mubarok"
#email = "jundimubarok74@gmail.com"
   image = "/img/profile-photo.png"
   imageQuality = 50
   headline = "*Ngobrol Lewat Tulisan Ringan*"
   bio = "Ngobrol Lewat Tulisan Ringan"
   links = [
      { instagram = "https://instagram.com/jundi.mubarok" },
      { threads = "https://www.threads.net/@jundi.mubarok" },
      { facebook = "https://facebook.com/jundipost" }
   ]
#     { mastodon = "https://mastodon.social/@jundimubarok"},
#     { instagram = "https://instagram.com/jundi.mubarok" },
#     { threads = "https://www.threads.net/@jundi.mubarok" },
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
# { telegram = "https://t.me/jundipost" }
#     ,
#     { mastodon = "https://mastodon.instance/@username" },
#     { medium = "https://medium.com/username" },
#     { tiktok = "https://tiktok.com/@username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { youtube = "https://youtube.com/username" },
#     { ko-fi = "https://ko-fi.com/username" },
